LDADD = -L$(link-out-dir)/../talib1 -ltalib1 \
	-L$(link-out-dir)/../talib2 -ltalib2 #\
#	-L$(link-out-dir)/../talib3 -ltalib3

# The UUID for the Trusted Application
BINARY=93038f64-871d-4773-b1f5-878697745eee

-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
